name: Nuget

on:
  workflow_dispatch:

jobs:

  nuget-called:
    runs-on: self-hosted

    env:
      API_KEY: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
    - uses: actions/checkout@v3

    - name: Add github nuget feed
      run: |
        dotnet nuget add source --username QuietData --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/QuietData/index.json"
      continue-on-error: true

    - name: Nuget push
      run: |
        dotnet nuget list source --format Detailed

        for i in $(ls .github/files/nuget/*.nupkg); do 
          dotnet nuget push $i --api-key ${{ env.API_KEY }} --source "github" --skip-duplicate
        done
